### PR TITLE
Create setup file

### PR DESCRIPTION
**Pull request by Krishnag09**
- added new setup file for the repo.

### CODE REVIEW

**Comment by Krishnag09** [comment]
@LuisanaMT2005 - is it better if i create the branch from main..

**Comment by LuisanaMT2005** [comment]
Thank you for your contribution.

**Comment by Krishnag09** [comment]
you are welcome. do you want to create a task for tests for me and assign it to me?

**Comment by LuisanaMT2005** [comment]
Of course, sorry for delete you from collaborators was a error from me.

**Comment by Krishnag09** [comment]
So when i read this - https://click.palletsprojects.com/en/8.1.x/setuptools/,  i am thinking if you need to change the way the commands are written and may be also create something like yourscript.py, and then make changes to setup.py to reflect the same.

**Comment by LuisanaMT2005** [comment]
Now I'm reading better and think the same, what you think about
- Copy the project struture on this part https://click.palletsprojects.com/en/8.1.x/setuptools/#scripts-in-packages.
- Write the @ck.group command on a separate script (ak yourscript.py) and there add the commands (with .add_command() method).
- Write the commands on scripts in yourpackage folder.

**Pull request merged**
